### ISSUE TITLE
Questions) code and results...

### ISSUE THREAD

**Issue by TaeniKim** [NahuelCostaCortez/Remaining-Useful-Life-Estimation-Variational#1]
I tried to execute your code.
I am curious about two questions.

1. main.py
  - RVE? RVAE?
	RVE = model.create_model(timesteps, ...
	model_callbacks = utils.get_callbacks(RVAE, x_train, y_train)

2. RULRVE.ipynb
  - Normal results when I use the pre-trained modes in the 'models' folder. 
    But When I create a models by 'RULRVE.ipynb' file, the results are different. 
    e.g. The color is reversed. yellow is on the right and the other is on the left.

I wonder if I'm missing anything.

**Comment by NahuelCostaCortez** [comment]
Hi TaeniKim,

RVAE is indeed a typo resulting from previous commits. It should be corrected now in the latest, thanks for pointing it out.

As for the notebook, that is normal to happen. In the end, the network tries to find the latent space that allows to make the best predictions, so depending on how it starts the optimization it can place the healthiest samples in the leftmost part or in the rightmost part. If several training runs are repeated that latent space may change, but you can adjust the color bar according to your preferences. In any case, the notebook is just an example, maybe using some callbacks from the utils file will help you to get better results (and consequently, a better latent space).

**Comment by TaeniKim** [comment]
Thank you for your prompt reply.
