### ISSUE TITLE
AttributeError: module     gradio.outputs has no attribute Plot

### ISSUE THREAD

**Issue by pROGRAMMERDATASCIENCE22** [NahuelCostaCortez/Remaining-Useful-Life-Estimation-Variational#4]
Hi,
We wanted to run the code for an RUL. When it comes to running the gradio file we get the above mentioned error in the 
outputs=[gr.outputs.Label(label="Prediction"),gr.outputs.Plot(type="auto", label="Latent space")],
line.
Kindly help out.

**Comment by NahuelCostaCortez** [comment]
Hi pROGRAMMERDATASCIENCE22,

At the time I build that demo the gradio version was 2.4.6. You may get this error if you are using the latest version and the outputs have been modified, which seems to be the most reasonable explanation.

Regards,

Nahuel
