### ISSUE TITLE
The number of sensors in training and testing.

### ISSUE THREAD

**Issue by sun-0704** [NahuelCostaCortez/Remaining-Useful-Life-Estimation-Variational#5]
Why are there only 5 sensors in the code instead of the 21 provided in the data set? Looking forward to your reply.

**Comment by sun-0704** [comment]
> Why are there only 5 sensors in the code instead of the 21 provided in the data set? Looking forward to your reply.

**Comment by NahuelCostaCortez** [comment]
Hi sun-0704,

It was just a matter of EDA and hyperparameter tunning. The selected sensors led to the best results.

Regards,
Nahuel
